### Sign up
POST http://localhost:3000/api/auth/signup
Content-Type: application/x-www-form-urlencoded

username=mzelinka
&password=123456

### Sign in
POST http://localhost:3000/api/auth/login
Content-Type: application/x-www-form-urlencoded

username=mzelinka
&password=123456

### Sign out
GET http://localhost:3000/api/auth/logout

### Get logged-in user
GET http://localhost:3000/api/auth/user