### Add child comment on parent
POST http://localhost:3000/api/comments/54
Content-Type: application/x-www-form-urlencoded

content=test

### Get comment for parent comment
GET http://localhost:3000/api/comments/3/comments

### Upvote comment
PATCH http://localhost:3000/api/comments/6/upvote