### Create post with valid data
POST http://localhost:3000/api/posts
Content-Type: application/x-www-form-urlencoded

title=testing
&content=testing

### Create post with invalid data
POST http://localhost:3000/api/posts
Content-Type: application/x-www-form-urlencoded

title=Multiple new macOS sandbox escape vulnerabilities

### Add comment to existing post
POST http://localhost:3000/api/posts/33/comment
Content-Type: application/x-www-form-urlencoded

content=testing

### Get all posts
GET http://localhost:3000/api/posts

### Get single post
GET http://localhost:3000/api/posts/31

### Get post comments
GET http://localhost:3000/api/posts/31/comments?includeChildren=true

### Upvote post
PATCH http://localhost:3000/api/posts/1/upvote